context:
  name: libyuv
  version: 1899

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  - git: https://github.com/lemenkov/libyuv.git
    branch: main
    patches:
      - fix_build.patch

build:
  number: 1000

requirements:
  run_exports:
    - ${{ name }}
  build:
    - ${{ compiler('cxx') }}
    - cmake
    - ninja
  host:
    - libjpeg-turbo

tests:
  - script:
      - if: unix
        then: test -f ${PREFIX}/include/libyuv.h

about:
  license: MIT
  license_file: LICENSE
  summary: libyuv is an open source project that includes YUV scaling and conversion functionality.
